import type { NextPage } from "next";
import Head from "next/head";
import styled from "styled-components";
import { Typography, ProductsList } from "../../components";

const HomeScreen = (props: HomeScreenProps) => {
  return (
    <>
      <Head>
        <title>GSCORE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Title>Get started with Gscore today!</Title>
        <ProductsList />
      </div>
    </>
  );
};

const Title = styled(Typography)`
  font: ${({ theme }) =>
    `${theme.typography.variants.specialHeading3.fontSize}/${theme.typography.variants.specialHeading3.lineHeight} ${theme.typography.fonts.thicccboi700}`};
  text-align: center;
  margin-bottom: 6.125rem;
`;

type HomeScreenProps = {};

export default HomeScreen;
