import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>GSCORE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Welcome </h1>
        <p>
          Lorem ipsum dolor sit amet consectetur, adipisicing elit. Repudiandae
          quam illum atque debitis, eveniet animi cumque sapiente harum libero
          minus, tempore beatae consequatur iure distinctio dolore optio vero
          laborum aperiam.
        </p>
        <p>
          Harum nam omnis consequuntur molestiae placeat ut exercitationem dicta
          laboriosam, dignissimos iusto. Magni consectetur aliquam tempora eius
          voluptatibus sint quaerat similique, totam ratione harum nemo? Rerum
          tenetur nemo aliquid repellendus aut ratione. Debitis accusantium
          cupiditate unde temporibus quos?
        </p>
        <p>
          Accusantium quo suscipit necessitatibus amet inventore. Reiciendis,
          consequuntur cumque? Eaque minus in enim magnam non eius repellat eum
          officia? Molestiae quae placeat nobis officia nemo optio aperiam nisi
          cupiditate iure veniam ad molestias consectetur, voluptates ut, hic
          blanditiis. Ratione nihil ea debitis aspernatur excepturi ad, quasi
          quis assumenda! Unde optio iure sapiente nihil nobis quidem quos earum
          ad dolores, voluptatum, sunt officia, quaerat pariatur dignissimos
          reprehenderit itaque? Pariatur cumque quam quos. Asperiores dolorem ut
          earum voluptate sunt consectetur odit totam natus veritatis sit,
          laudantium libero autem modi ipsa maxime et explicabo nesciunt. Saepe
          eos accusantium voluptatibus velit architecto necessitatibus labore
          unde sapiente suscipit earum illum, tempora distinctio, inventore,
          veritatis quae recusandae commodi. Commodi quae accusamus veniam
          similique maiores mollitia vel, temporibus adipisci.
        </p>
      </div>
    </>
  );
};

export default Home;
